// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-my-projects.ts
import { createClient } from "npm:@supabase/supabase-js@^2.97.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^4.4.3";
function sb(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_projects_default = defineTool({
  name: "list_my_projects",
  title: "List my projects",
  description: "List AI-project evaluations the signed-in user can access (own or as a team member). Returns id, title, status, join code and last update.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).optional().describe("Max rows to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await sb(ctx).from("projects").select("id, title, status, join_code, updated_at, created_by, completion_pct").is("deleted_at", null).order("updated_at", { ascending: false }).limit(limit ?? 50);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { projects: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-project.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.97.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^4.4.3";
function sb2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_project_default = defineTool2({
  name: "get_project",
  title: "Get project details",
  description: "Return a single project's metadata plus its saved form responses (per field key). The caller must have access to the project via ownership, membership or being a consultant.",
  inputSchema: {
    project_id: z2.string().uuid().describe("Project UUID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ project_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const client = sb2(ctx);
    const [projectRes, responsesRes] = await Promise.all([
      client.from("projects").select("id, title, status, join_code, completion_pct, created_at, updated_at, created_by").eq("id", project_id).is("deleted_at", null).maybeSingle(),
      client.from("form_responses").select("field_key, field_value, table_data, updated_at, updated_by").eq("project_id", project_id)
    ]);
    if (projectRes.error) {
      return { content: [{ type: "text", text: projectRes.error.message }], isError: true };
    }
    if (!projectRes.data) {
      return { content: [{ type: "text", text: "Project not found or access denied." }], isError: true };
    }
    if (responsesRes.error) {
      return { content: [{ type: "text", text: responsesRes.error.message }], isError: true };
    }
    const payload = { project: projectRes.data, responses: responsesRes.data ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-project-comments.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.97.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^4.4.3";
function sb3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_project_comments_default = defineTool3({
  name: "list_project_comments",
  title: "List project comments",
  description: "List comments (observations) left on a project. Optionally filter by field_key. Returns author id, field key, text, status and timestamps.",
  inputSchema: {
    project_id: z3.string().uuid().describe("Project UUID."),
    field_key: z3.string().optional().describe("Optional field key to filter (e.g. 'p-1', 'eth-dat3').")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ project_id, field_key }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let query = sb3(ctx).from("comments").select("id, project_id, field_key, author_id, text, status, parent_id, created_at, updated_at").eq("project_id", project_id).is("deleted_at", null).order("created_at", { ascending: true });
    if (field_key) query = query.eq("field_key", field_key);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { comments: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/add-comment.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.97.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^4.4.3";
function sb4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var add_comment_default = defineTool4({
  name: "add_comment",
  title: "Add a comment on a field",
  description: "Add a comment (observation) on a specific field of a project. The author is always the signed-in user; text is required.",
  inputSchema: {
    project_id: z4.string().uuid().describe("Project UUID."),
    field_key: z4.string().min(1).describe("Field key the comment refers to (e.g. 'p-1', 'obj-1')."),
    text: z4.string().trim().min(1).describe("Comment text."),
    parent_id: z4.string().uuid().optional().describe("Optional parent comment id when replying to a thread.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ project_id, field_key, text, parent_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await sb4(ctx).from("comments").insert({
      project_id,
      field_key,
      text,
      parent_id: parent_id ?? null,
      author_id: ctx.getUserId()
    }).select("id, project_id, field_key, author_id, text, created_at").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Comment created: ${data.id}` }],
      structuredContent: { comment: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "sdxwjenheoveabaqqwef";
var mcp_default = defineMcp({
  name: "goblab-eval-mcp",
  title: "Herramienta de Evaluaci\xF3n de Proyectos de IA",
  version: "0.1.0",
  instructions: "Tools to browse and comment on AI-project evaluations built in the GobLab IA evaluation portal. Use `list_my_projects` to discover projects the signed-in user can access, `get_project` to read a project's saved form answers, `list_project_comments` to read observations, and `add_comment` to leave a new observation on a specific field.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_my_projects_default, get_project_default, list_project_comments_default, add_comment_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
